### ISSUE TITLE
[BUG] had to change "docker compose" to "docker-compose"

### ISSUE THREAD

**Issue by dmaynor** [peasead/elastic-container#13]
**Describe the bug**
Running ./elastic-container.sh -v start would result in an error from docker.
➜  elastic-container git:(main) ✗ ./elastic-container.sh -v start  
Passphrase has been reset. Proceeding.
Starting Elastic Stack network and containers
unknown shorthand flag: 'd' in -d
See 'docker --help'.

**To Reproduce**
1. git clone the repo locally and cd to it.
2. run ./elastic-container.sh
3. See error

**Expected behavior**
Docker containers are provisioned and started. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04

**Additional context**
I saw a commuted change that replaced "docker-compose" with "docker compose". I had to switch it back and everything ran fine.

**Comment by peasead** [comment]
Hey @dmaynor, thanks for the Issue.

Do you have the `docker-compose-plugin` installed from the [Docker documentation](https://docs.docker.com/engine/install/ubuntu/#install-docker-engine)?

**Comment by peasead** [comment]
You can check `apt-cache policy docker-compose-plugin` on Ubuntu or `dnf list installed | grep docker-compose-plugin` on RPM distros.

#8 had the same problem, the Docker documentation fixed their issue.
