### ISSUE TITLE
unknown shorthand flag d

### ISSUE THREAD

**Issue by mellonaut** [peasead/elastic-container#15]
When I try to run the helper script, I get an error about unkown shorthand flag d

Output:

 ./elastic-container.sh start
Passphrase has been reset. Proceeding.
Starting Elastic Stack network and containers
unknown shorthand flag: 'd' in -d
See 'docker --help'.

**Comment by peasead** [comment]
Hello @mellonaut 

What OS are you using?

**Comment by DefSecSentinel** [comment]
@mellonaut that usually means you are missing one of the pre-reqs (probably curl or jq) or don't have the docker-compose-plugin installed

**Comment by mellonaut** [comment]
I’m on Ubuntu 20, I googled around and saw about docker-compose V1 vs V2 and followed a guide for replacing the binary and using compose-switch but still a no-go. Think if I try it on a fresh 22 VM and installed docker V2 it would work?

**Comment by peasead** [comment]
All the issues that people have had were resolved when they re-looked at the prerequisites and followed them specifically.

Just to underscore, there's a difference between **docker-compose** and **docker-compose-plugin**. Based on your comment on v1/v2 versions of docker-compose, I suspect that you don't have the Docker prerequisites installed.

Please check out the Docker instructions and LMK how that works - https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository
