### ISSUE TITLE
[BUG] Installation process fails Container kibana Waiting 

### ISSUE THREAD

**Issue by security101** [peasead/elastic-container#18]
**Describe the bug**
Installation process does not complete and indicates waiting for Container Kibana

**To Reproduce**
./elastic-container.sh start  
Passphrase has been reset. Proceeding.
Starting Elastic Stack network and containers
[+] Running 7/8
 ⠿ Network elastic-container_default       Created                                                                             0.4s
 ⠿ Volume "elastic-container_certs"        Created                                                                             0.0s
 ⠿ Volume "elastic-container_kibanadata"   Created                                                                             0.0s
 ⠿ Volume "elastic-container_esdata01"     Created                                                                             0.0s
 ⠿ Container elasticsearch-security-setup  Healthy                                                                             7.7s
 ⠿ Container elasticsearch                 Healthy                                                                            30.3s
 ⠿ Container kibana                        Waiting                                                                            35.7s
 ⠿ Container fleet-server                  Created                                                                             0.1s
container for service "kibana" is unhealthy

**Expected behavior**
Installation process terminates successful means all containers reach the status Healthy 

**Screenshots**

Checking log files:
docker-compose logs | fgrep kibana
elasticsearch-security-setup  |    creating: config/certs/kibana/
elasticsearch-security-setup  |   inflating: config/certs/kibana/kibana.crt  
elasticsearch-security-setup  |   inflating: config/certs/kibana/kibana.key  
elasticsearch-security-setup  | Setting kibana_system password
elasticsearch                 | {"@timestamp":"2022-10-28T12:03:24.770Z", "log.level": "INFO", "message":"loaded module [kibana]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.plugins.PluginsService","elasticsearch.node.name":"elasticsearch","elasticsearch.cluster.name":"elastic-container"}
elasticsearch                 | {"@timestamp":"2022-10-28T12:03:34.112Z", "log.level": "INFO", "message":"adding template [.monitoring-kibana] for index patterns [.monitoring-kibana-7-*]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[elasticsearch][masterService#updateTask][T#1]","log.logger":"org.elasticsearch.cluster.metadata.MetadataIndexTemplateService","elasticsearch.cluster.uuid":"RQTcZuopT8y6bewOzx83oQ","elasticsearch.node.id":"4GSTeBR4S6W4UYaYbqaEyg","elasticsearch.node.name":"elasticsearch","elasticsearch.cluster.name":"elastic-container"}
elasticsearch                 | {"@timestamp":"2022-10-28T12:03:34.224Z", "log.level": "INFO", "message":"adding index template [.monitoring-kibana-mb] for index patterns [.monitoring-kibana-8-*]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[elasticsearch][masterService#updateTask][T#1]","log.logger":"org.elasticsearch.cluster.metadata.MetadataIndexTemplateService","elasticsearch.cluster.uuid":"RQTcZuopT8y6bewOzx83oQ","elasticsearch.node.id":"4GSTeBR4S6W4UYaYbqaEyg","elasticsearch.node.name":"elasticsearch","elasticsearch.cluster.name":"elastic-container"}
kibana                        | FATAL CLI ERROR Error: EACCES: permission denied, open '/usr/share/kibana/config/kibana.yml'
kibana                        |     at Object.openSync (node:fs:594:3)
kibana                        |     at readFileSync (node:fs:462:35)
kibana                        |     at readYaml (/usr/share/kibana/node_modules/@kbn/config/target_node/raw/read_config.js:25:69)
kibana                        |     at getConfigFromFiles (/usr/share/kibana/node_modules/@kbn/config/target_node/raw/read_config.js:57:18)
kibana                        |     at RawConfigService.loadConfig (/usr/share/kibana/node_modules/@kbn/config/target_node/raw/raw_config_service.js:56:70)
kibana                        |     at bootstrap (/usr/share/kibana/src/core/server/bootstrap.js:57:20)
kibana                        |     at Command.<anonymous> (/usr/share/kibana/src/cli/serve/serve.js:216:11)
kibana                        |     at Command.<anonymous> (/usr/share/kibana/src/cli/command.js:102:20)
kibana                        |     at Command.listener (/usr/share/kibana/node_modules/commander/index.js:370:29)
kibana                        |     at Command.emit (node:events:513:28)
kibana                        |     at Command.parseArgs (/usr/share/kibana/node_modules/commander/index.js:892:12)
kibana                        |     at Command.parse (/usr/share/kibana/node_modules/commander/index.js:642:21)
kibana                        |     at Object.<anonymous> (/usr/share/kibana/src/cli/cli.js:49:9)
kibana                        |     at Module._compile (node:internal/modules/cjs/loader:1126:14)
kibana                        |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
kibana                        |     at Module.load (node:internal/modules/cjs/loader:1004:32)
kibana                        |     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
kibana                        |     at Module.require (node:internal/modules/cjs/loader:1028:19)
kibana                        |     at Module.Hook._require.Module.require (/usr/share/kibana/node_modules/require-in-the-middle/index.js:101:39)
kibana                        |     at Module.Hook._require.Module.require (/usr/share/kibana/node_modules/require-in-the-middle/index.js:101:39)
kibana                        |     at Module.Hook._require.Module.require (/usr/share/kibana/node_modules/require-in-the-middle/index.js:101:39)
kibana                        |     at Module.Hook._require.Module.require (/usr/share/kibana/node_modules/require-in-the-middle/index.js:101:39)
kibana                        |     at Module.Hook._require.Module.require (/usr/share/kibana/node_modules/require-in-the-middle/index.js:101:39)
kibana                        |     at Module.Hook._require.Module.require (/usr/share/kibana/node_modules/require-in-the-middle/index.js:101:39)
kibana                        |     at require (node:internal/modules/cjs/helpers:102:18)
kibana                        |     at Object.<anonymous> (/usr/share/kibana/src/cli/dist.js:16:1)
kibana                        |     at Module._compile (node:internal/modules/cjs/loader:1126:14)
kibana                        |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
kibana                        |     at Module.load (node:internal/modules/cjs/loader:1004:32)
kibana                        |     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
kibana                        |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
kibana                        |     at node:internal/main/run_main_module:17:47

**Desktop (please complete the following information):**
 - OS: Centos 8

Linux <my_hostname> 4.18.0-394.el8.x86_64 #1 SMP Tue May 31 16:19:11 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

sudo yum install jq git curl
Last metadata expiration check: 0:53:56 ago on Fri 28 Oct 2022 11:00:32 AM UTC.
Package jq-1.6-3.el8.x86_64 is already installed.
Package git-2.31.1-2.el8.x86_64 is already installed.
Package curl-7.61.1-25.el8.x86_64 is already installed.
Dependencies resolved.

sudo yum install docker-compose-plugin
Last metadata expiration check: 0:59:40 ago on Fri 28 Oct 2022 11:00:32 AM UTC.
Package docker-compose-plugin-2.12.2-3.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

**Additional context**
sudo systemctl restart docker after plugin installation

**Comment by peasead** [comment]
Thanks, @security101 

We've not experienced this issue before. 

This looks to be related?

```
kibana | FATAL CLI ERROR Error: EACCES: permission denied, open '/usr/share/kibana/config/kibana.yml'
```

What're your permissions on `kibana.yml` (including the `Z` switch for the SELinux context)? Mine is 

```
ls -lZ elastic-container/kibana.yml
-rw-rw-r--. 1 variable variable unconfined_u:object_r:user_home_t:s0 441 Oct 28 16:14 elastic-container/kibana.yml
```

I just ran a test on CentOS 8 (stream FWIW).
```
$ ./elastic-container.sh start
Passphrase has been reset. Proceeding.
Starting Elastic Stack network and containers
[+] Running 8/8
 ⠿ Network elastic-container_default       Created                                                                                                                              0.2s
 ⠿ Volume "elastic-container_certs"        Created                                                                                                                              0.0s
 ⠿ Volume "elastic-container_esdata01"     Created                                                                                                                              0.0s
 ⠿ Volume "elastic-container_kibanadata"   Created                                                                                                                              0.0s
 ⠿ Container elasticsearch-security-setup  Healthy                                                                                                                              4.2s
 ⠿ Container elasticsearch                 Healthy                                                                                                                             27.7s
 ⠿ Container kibana                        Healthy                                                                                                                             58.2s
 ⠿ Container fleet-server                  Started                                                                                                                             59.5s

Attempting to enable the Detection Engine and install prebuilt Detection Rules

Kibana is up. Proceeding

Detection engine enabled. Installing prepackaged rules.

Prepackaged rules installed!

No detection rules enabled in the .env file, skipping detection rules enablement

Waiting 40 seconds for Fleet Server setup

Populating Fleet Settings

READY SET GO!

Browse to https://localhost:5601
Username: elastic
Passphrase: elastic

[variable@localhost elastic-container]$ ./elastic-container.sh status
NAME                           COMMAND                  SERVICE             STATUS              PORTS
elasticsearch                  "/bin/tini -- /usr/l…"   elasticsearch       running (healthy)   0.0.0.0:9200->9200/tcp, :::9200->9200/tcp, 9300/tcp
fleet-server                   "/usr/bin/tini -- /u…"   fleet-server        running             0.0.0.0:8220->8220/tcp, :::8220->8220/tcp
kibana                         "/bin/tini -- /usr/l…"   kibana              running (healthy)   0.0.0.0:5601->5601/tcp, :::5601->5601/tcp
[variable@localhost elastic-container]$
```

**Comment by peasead** [comment]
Unresponsive. Reopen if persists.
