### ISSUE TITLE
[DOCUMENTATION] Readme for Arch Linux users

### ISSUE THREAD

**Issue by kmahyyg** [peasead/elastic-container#19]
**Is your documentation related to a problem? Please describe.**
Yes, failed to run shell script.

**Describe the documentation you'd like**
Not failed to run this script.

**Describe alternatives you've considered**
Nope.

**Additional context**
1. Arch Linux user should additionally install `inetutils` to have `hostname`
2. Change the shell script from `hostname -I` to `hostname -i` when you running it on latest Arch.

**Comment by peasead** [comment]
Thanks @kmahyyg

Would you like to make a PR to the documentation or do you want me to do the update?

Just asking because you brought up a good idea and want to make sure you get credit if you want.

**Comment by kmahyyg** [comment]
> 

I want you to made this update. Thanks for your excellent work.
