### ISSUE TITLE
[BUG] Error Loading Config File

### ISSUE THREAD

**Issue by bigverm23** [peasead/elastic-container#22]
**Describe the bug**
script never runs and displays error about root config
```
Passphrase has been reset. Proceeding.
Starting Elastic Stack network and containers
WARNING: Error loading config file: /root/.docker/config.json: read /root/.docker/config.json: is a directory
unknown shorthand flag: 'd' in -d
```

**To Reproduce**

1. Git clone this repo
2. Install prerequisites (see below)
3. Change into the elastic-container/ folder
4. Change the default password of "changeme" in the .env file
5. Bulk enable pre-built detection rules by OS in the .env file (not required, see usage below)
6. Make the elastic-container.sh shell script executable by running chmod +x elastic-container.sh
7. Execute the elastic-container.sh shell script with the start argument ./elastic-container start

**Expected behavior**
...
 ⠿ Container elasticsearch-security-setup  Healthy 7.3s
 ⠿ Container elasticsearch                 Healthy 39.3s
 ⠿ Container kibana                        Healthy 59.3s
 ⠿ Container elastic-agent                 Started 59.7s

Attempting to enable the Detection Engine and Prebuilt-Detection Rules

Kibana is up. Proceeding

Detection engine enabled. Installing prepackaged rules.

Prepackaged rules installed!

Waiting 40 seconds for Fleet Server setup

Populating Fleet Settings

READY SET GO!

Browse to https://localhost:5601
Username: elastic
Passphrase: not-the-default!

**Screenshots**
`xxxxxxx@ken-pc:~/docker/elastic-container$ sudo ./elastic-container.sh -v start
Passphrase has been reset. Proceeding.
Starting Elastic Stack network and containers
WARNING: Error loading config file: /root/.docker/config.json: read /root/.docker/config.json: is a directory
unknown shorthand flag: 'd' in -d
See 'docker --help'.`

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 22.10

**Comment by peasead** [comment]
Hey @bigverm23 

Can you verify that the `docker-compose-plugin` plugin is installed (which is different than Docker Compose)? Whenever I see the error you showed above, it's because that plugin isn't installed.

https://docs.docker.com/engine/install/ubuntu/#:~:text=To%20install%20the%20latest%20version%2C%20run,%24

**Comment by bigverm23** [comment]
that was the issue, thanks it works now.
