### ISSUE TITLE
[ENHANCEMENT] Support Podman

### ISSUE THREAD

**Issue by peasead** [peasead/elastic-container#26]
Support Podman as a container technology for ECP.

**Comment by peasead** [comment]
@koelslaw can you update the `README.md` to include instructions on how to install Podman?

I don't see it in my Rocky builds. I can't check right now, but I feel like its as simple as `dnf install podman` or `apt install podman`? If so, that'd be easier for Linux installations all around.

Can you check that and LMK what you recommend?

**Comment by koelslaw** [comment]
Podman/podman-compose is completely ignoring health checks at the moment and tries to stand up fleet server immediately. This wouldn't necessarily be an issue but It also ignore the restart flag after a certain amount of time or attempts (not sure which). Fleet containers stops restarting and your left without it. If you run shell or start the container individually it takes right off. 🤷 More work to try and figure this out.

**Comment by peasead** [comment]
We'll reopen if this makes progress.
