### ISSUE TITLE
[ENHANCEMENT] Deployment in Production with large scale of endpoint

### ISSUE THREAD

**Issue by ilumitr** [peasead/elastic-container#27]
**Is your feature request related to a problem? Please describe.**
I would like to request a new feature for the project to enable deployment in a production that can serve large scale of endpoint. I love the idea of simple deployment just using docker.  I believe this makes elastic security easier for mass adoption.

**Describe the solution you'd like**
I would like to see the project enhanced to support deployment in a production multi-host environment using Docker Swarm or Kubernetes,... This would allow Elastic Security to be easily managed and scaled across multiple hosts, providing high availability and efficient resource utilization.

**Describe alternatives you've considered**
Maybe start with simple Multi-node docker-compose? 

**Additional context**
The addition of this feature would have a significant impact on the usability and adoption of the project. It would allow organizations to deploy Elastic Security in production environments that utilize Docker Swarm or Kubernetes for orchestration, unlocking the benefits of scalability, high availability, and ease of management. I believe it would greatly enhance the project's capabilities and broaden its applicability in real-world scenarios.

**Comment by peasead** [comment]
Thanks for checking out the project, @ilumitr 

The goal of the project is to rapidly deploy an environment for testing, not production.

That said, we're an open project and you're welcome to fork or branch and contribute. Pull requests are always welcome.
