### ISSUE TITLE
Request for Traefik Docker Compose Labels 

### ISSUE THREAD

**Issue by ksecurity45** [peasead/elastic-container#35]
Issue Description:

I'm currently utilizing Cloudflare DNS and TLS within my Traefik setup, but I'm facing challenges when attempting to configure these aspects using Traefik labels within my Docker Compose file. I would greatly appreciate guidance and assistance in establishing the requisite labels to ensure the seamless functioning of this configuration.

Problem Overview:

My Traefik setup involves routing traffic to both Kibana and Elastic. To maintain secure internal connections, both Kibana and Elastic mandate TLS for incoming requests. I'm currently encountering difficulties in configuring Traefik labels to effectively handle self-signed certificates and manage TLS for these services.

Request:

I kindly request assistance in providing the necessary Docker Compose labels for ensuring the successful operation of self-signed certificates with Traefik.

Thank you for your support.

**Comment by peasead** [comment]
Thanks for checking out the project, @ksecurity45 

I don't know the labels that you'd need for Traefik. I'm sure you may have already searched, but maybe this will help.

That said, this isn't an issue with the project, I'm going to close this.
