### ISSUE TITLE
[BUG] Fleet container not enrolling as agent

### ISSUE THREAD

**Issue by ak11234** [peasead/elastic-container#37]
**Describe the bug**
Fleet server setup fails on fresh start with brand new clean vm of Ubuntu 22.04.03 LTS.

**To Reproduce**
Fresh install ubuntu server, install docker, jq, (git and curl already present). Clone repo, set env params, execute `sudo ./elastic-container.sh start`. Log into kibana, go to fleet in side menu, find no fleet server present despite the policies having been created.

In the logs of the fleet container, you can see it waiting for a server:  `{"log.level":"info","@timestamp":"2023-12-25T22:04:51.912Z","message":"Waiting on fleet-server input to be added to policy: fleet-server-policy","component":{"binary":"fleet-server","dataset":"elastic_agent.fleet_server","id":"fleet-server-default","type":"fleet-server"},"log":{"source":"fleet-server-default"},"ecs.version":"1.6.0","service.name":"fleet-server","service.type":"fleet-server","state":"STARTING","ecs.version":"1.6.0"}`

To try and see what went wrong, I modified the script and removed the redirect to null on the set_fleet_value, and saw that the final output was an error `  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 50220  100 50219  100     1  93915      1  0:00:01 --:--:--  0:00:01 94221
{
  "statusCode": 404,
  "error": "Not Found",
  "message": "Saved object [ingest-agent-policies/null] not found"
}`

**Expected behavior**
A fleet server listed in the fleet page of kibana.

**Screenshots**
See details above with log messages. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.03 LTS (kernel 5.15.0-91-generic)
 - Browser [e.g. chrome, safari]: opera latest
 - Version: all versions the latest that apt or git provided to me, listed below
 - this Git repo pulled from 12/23
 - ELK set in env is latest, 8.11.13
 - curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.16 Release-Date: 2022-01-05
 - jq-1.6
 - Docker version 24.0.7

**Additional context**

**Comment by peasead** [comment]
👋 @ak11234 

Can you run `./elastic-container.sh status` and `sudo apt list --all-versions | grep -i docker`, and post the results here? Just want to make sure you've got all the right packages.

When you installed Docker, did you follow all of [these specific](https://docs.docker.com/engine/install/ubuntu/) instructions? Usually, the issue is that all the instructions under "Install the Docker packages" are sometimes adapted or skipped.

**Comment by ak11234** [comment]
Hi @peasead, I was able to resolve it by destroying everything and starting again, this time using the absolute defaults, not modifying which rules I had set to 1 or 0 to enable or disable.
