### ISSUE TITLE
[BUG]"Failed to connect to backoff(elasticsearch(http://172.31.23.214:9200))

### ISSUE THREAD

**Issue by saidhfm** [peasead/elastic-container#50]
{"log.level":"error","@timestamp":"2024-08-20T21:30:33.973Z","message":"Failed to connect to backoff(elasticsearch(http://172.31.23.214:9200)): Get \"http://172.31.23.214:9200\": EOF","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"system/metrics-default","type":"system/metrics"},"log":{"source":"system/metrics-default"},"log.logger":"publisher_pipeline_output","log.origin":{"file.line":148,"file.name":"pipeline/client_worker.go","function":"github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*netClientWorker).run"},"service.name":"metricbeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}

**To Reproduce**
1. Go to 'fleet'
2. Click on '.Add agent'
3. Scroll down to 'enroll in fleet'->copy commands -> paste in the agent machine
4. See error logs of elast agent in the agent machine -> Failed to connect to backoff(

**Expected behavior**
The logs should reach elsticsearch from agent

**Screenshots**
<img width="1251" alt="image" src="https://github.com/user-attachments/assets/36679354-dbef-4a27-8bff-1feacad271f7">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Ubuntu
 - Browser [e.g. chrome, safari] -NA

**Additional context**

**Comment by peasead** [comment]
What're your resources assigned to your host?

**Comment by saidhfm** [comment]
Its aws ec2 instance with 8gb Ram 2 core cpu and 200gb storage and imdsv1

**Comment by saidhfm** [comment]
Thanks This got resolved, I have added a role to ec2 instance and that got fixed
