### ISSUE TITLE
Detection Engine setup failed

### ISSUE THREAD

**Issue by benmoree** [peasead/elastic-container#8]
I've attempted to run this project on my Ubuntu 20.04.5 LTS VM. After installing prerequisites, updating, cloning, and changing the default credentials I ran the './elastic-container.sh start' command but the detection engine setup failed. 

Here is the output:

root@ubuntu:/home/ben/elastic-container# ./elastic-container.sh start
Passphrase has been reset. Proceeding.
Starting Elastic Stack network and containers
Creating network "elastic-container_default" with the default driver
Creating volume "elastic-container_certs" with local driver
Creating volume "elastic-container_esdata01" with local driver
Creating volume "elastic-container_kibanadata" with local driver
Creating elasticsearch-security-setup ... done
Creating elasticsearch                ... done
Creating kibana                       ... done
Creating fleet-server                 ... done

Attempting to enable the Detection Engine and install prebuilt Detection Rules

Kibana is up. Proceeding

Detection Engine setup failed :-(
root@ubuntu:/home/ben/elastic-container#

I'm not sure how else to describe what occurred.

**Comment by peasead** [comment]
Hey, @benmoree thanks for the issue.

We hadn't experienced that with our testing, but I'll spin up a fresh Ubuntu 20.04.5 LTS and see if I can replicate that.

While I check that, can you run `jq --version` and `curl --version`? Both cURL and jq are used enable the Detection Engine using the Kibana APIs.

**Comment by peasead** [comment]
Okay, I did a test and was able to get it to execute fully. 

```
...
Creating fleet-server                 ... done

Attempting to enable the Detection Engine and install prebuilt Detection Rules

Kibana is up. Proceeding

Detection engine enabled. Installing prepackaged rules.

Prepackaged rules installed!

Waiting 40 seconds for Fleet Server setup

Populating Fleet Settings

READY SET GO!

Browse to https://localhost:5601
Username: elastic
Passphrase: -
```

Here are my versions, do yours match?
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```

```
$ jq --version
jq-1.6

$ curl --version
curl 7.68.0 (aarch64-unknown-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
```

**Comment by OzzyKampha** [comment]
I found a typo in the elastic-container.sh on line 90, it should be docker-compose , not docker compose  ` fingerprint=$(docker compose exec -w /usr/share/elasticsearch/config/certs/ca elasticsearch cat ca.crt | openssl x509 -noout -fingerprint -sha256 | cut -d "=" -f 2 | tr -d :)`

**Comment by peasead** [comment]
> I found a typo in the elastic-container.sh on line 90, it should not be "docker compose" ` fingerprint=$(docker compose exec -w /usr/share/elasticsearch/config/certs/ca elasticsearch cat ca.crt | openssl x509 -noout -fingerprint -sha256 | cut -d "=" -f 2 | tr -d :)` If you change it to docker-compose it should work

Moved this to #9

**Comment by peasead** [comment]
Thanks @benmoree I think we're good on this. If you're still having an issue, we can reopen.

**Comment by benmoree** [comment]
@peasead Sorry for the delay in responding. I've been trying the fix you suggested but still have the same issue. I've also checked my versions of Ubuntu, jq, and curl, all are the same versions as yours...

```
ben@ubuntu:~/elastic-container$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```
`ben@ubuntu:~/elastic-container$ jq --version
jq-1.6

ben@ubuntu:~/elastic-container$ curl --version
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
`

**Comment by peasead** [comment]
Can you do a fresh `git pull` from the `main` branch and see if that works?

**Comment by benmoree** [comment]
After doing a fresh git pull, when running the `./elastic-container.sh start` command I get a docker error:

```
sudo ./elastic-container.sh start

[sudo] password for ben: 
Passphrase has been reset. Proceeding.
Starting Elastic Stack network and containers
unknown shorthand flag: 'd' in -d
See 'docker --help'.
```

**Comment by peasead** [comment]
@benmoree do you have the `docker-compose-plugin` installed from the prerequisites? It's outlined in the [Docker documentation](https://docs.docker.com/engine/install/ubuntu/#install-docker-engine).

**Comment by benmoree** [comment]
I do have ```docker-compose``` installed:

```
sudo apt-get install docker-compose

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
docker-compose is already the newest version (1.29.2-1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
```

**Comment by benmoree** [comment]
@peasead A side note with the latest updates to the project, I tried using both Ubuntu 22.04.1 and CentOS-7 today and got the same Docker error...

**Comment by peasead** [comment]
@benmoree I am pretty sure the issue is that you're using `docker-compose` and not the `docker-compose-plugin`. They're different.

Can you try the [Docker documentation](https://docs.docker.com/engine/install/ubuntu/)? We've troubleshot this in multiple RPM and Ubuntu VMs today with no issue once we followed the Docker steps to install the Docker Engine.

**Comment by benmoree** [comment]
Yeah I'll try that.

**Comment by peasead** [comment]
Great news, @benmoree !

Let us know if you have any additional issues!
